# Generated by Django 4.2.2 on 2023-06-07 11:29

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthname', models.CharField(max_length=100)),
                ('surename', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('town_zip', models.CharField(max_length=100)),
                ('insurance', models.CharField(choices=[('111', '111: VZP'), ('201', '201: Vojenská zdravotní pojišťovna České republiky'), ('205', '205: Česká průmyslová zdravotní pojišťovna'), ('207', '207: Oborová zdravotní pojišťovna zaměstnanců bank, pojišťoven a stavebnictví'), ('209', '209: Zaměstnanecká pojišťovna Škoda'), ('211', '211: Zdravotní pojišťovna ministerstva vnitra České republiky'), ('213', '213: RBP, zdravotní pojišťovna')], max_length=3)),
                ('parrent', models.CharField(max_length=100)),
                ('parrents_phone', blog.models.PhoneField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{12,15}$')])),
                ('parrents_email', models.EmailField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
